dbhost: localhost
debug: false
server:
  port: 8080
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${dbhost}:3306/blog
    username: blog
    password: RbM8u$slkomV5
  flyway:
    enabled: false

    #logging:
    #level:
    #root: "info"
    #org.springframework: "info"
    #org.springframework.web: "info"
    #org.hibernate: "info"
    #org.hibernate.SQL=DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder=TRACE
    #o.h.e.j.s.SqlStatementLogger