dbhost: localhost
debug: false
server.port: 8080

spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://${dbhost}:3306/blog
spring.datasource.username: blog
spring.datasource.password: RbM8u$slkomV5
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.flyway.enabled: true


#spring.web.resources.static-locations: classpath:\static\,classpath:\upload\
#spring.servlet.multipart.location: ${java.io.tmpdir}
# Spring Boot 1.4
#spring.http.multipart.max-file-size: 10MB
#spring.http.multipart.max-request-size: 10MB
spring.servlet.multipart.enabled: true
spring.servlet.multipart.max-file-size: ${blog.maxUploadSize}
spring.servlet.multipart.max-request-size: ${blog.maxUploadSize}



blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  serverTimeZone: Europe/Moscow
  captchaDeleteTimeout: 3600
  prohibitedTags: script|embedded|link|header|object|html|body
  uploadDir: upload # загружаем в папку откуда запущено приложение
  maxUploadSize: 5MB

    #logging:
    #level:
    #root: "info"
    #org.springframework: "info"
    #org.springframework.web: "info"
    #org.hibernate: "info"
    #org.hibernate.SQL=DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder=TRACE
    #o.h.e.j.s.SqlStatementLogger