dbhost: localhost
debug: false
server.port: 8080

spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://${dbhost}:3306/blog
spring.datasource.username: blog
spring.datasource.password: RbM8u$slkomV5
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.flyway.enabled: false

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  serverTimeZone: Europe/Moscow
  hashAlgorithm: md5
  postSortModes:
    RECENT:
        fieldName: time
        direction: DESC
    POPULAR:
        fieldName: "COUNT(c.id)"
        direction: DESC
        sortUnsafe: true
    BEST:
        fieldName: "COUNT(v.id)"
        direction: DESC
        sortUnsafe: true
    EARLY:
        fieldName: time
        direction: ASC


    #logging:
    #level:
    #root: "info"
    #org.springframework: "info"
    #org.springframework.web: "info"
    #org.hibernate: "info"
    #org.hibernate.SQL=DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder=TRACE
    #o.h.e.j.s.SqlStatementLogger