debug: false
server.port: ${PORT:8080}

# Spring Boot persistence config
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:${DB_URL:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=${blog.serverTimeZone}&useLegacyDatetimeCode=false}
spring.datasource.username: blog
spring.datasource.password: RbM8u$slkomV5
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect # spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.time_zone: ${blog.serverTimeZone}

#OSiV is disabled to avoid perfomance issues
spring.jpa.open-in-view: false

# show SQL
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.format_sql: true

# Spring Boot DB Migration control via Flywqy
spring.flyway.enabled: true
logging.level.spring.flyway: trace

# Spring Boot upload files config
#spring.web.resources.static-locations: classpath:\static\,classpath:\upload\
#spring.servlet.multipart.location: ${java.io.tmpdir}
# Spring Boot <1.4
#spring.http.multipart.max-file-size: 10MB
#spring.http.multipart.max-request-size: 10MB
# Spring Boot >1.4
spring.servlet.multipart.enabled: true
spring.servlet.multipart.max-file-size: ${blog.maxUploadSize}
spring.servlet.multipart.max-request-size: ${blog.maxUploadSize}

# Spring Boot Mail config
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: ${GMAIL_USERNAME}
spring.mail.password: ${GMAIL_APPPASS}
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

# blog settings
blog:
  title: JStory
  siteUrl: ${APP_URL:http://localhost:${server.port}}
  subtitle: Блог о программировании на Java
  phone: +7 123 123-45-67
  email: support@blogengine.com
  copyright: Александр Иванов
  copyrightFrom: 2021
  serverTimeZone: America/Los_Angeles #Europe/Moscow
  captchaDeleteTimeout: 3600
  permittedTags: h1|h2|h3|h4|h5|h6|bold|strong|u|p|div|span|font|code|img
  uploadDir: upload # загружаем в папку откуда запущено приложение
  maxUploadSize: 5MB