-- ALTER TABLE global_settings ADD CONSTRAINT GLOBALSETTINGS_CODE_U UNIQUE (code);

ALTER TABLE post_comments ADD CONSTRAINT POSTCOMMENTS_PARENT_ID_FK FOREIGN KEY (parent_id) REFERENCES post_comments (id);

ALTER TABLE post_comments ADD CONSTRAINT POSTCOMMENTS_POST_ID_FK FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE post_comments ADD CONSTRAINT POSTCOMMENTS_USER_ID_FK FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE post_votes ADD CONSTRAINT POSTVOTES_POST_ID_FK FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE post_votes ADD CONSTRAINT POSTVOTES_USER_ID_FK FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE posts ADD CONSTRAINT POSTS_MODERATOR_ID_FK FOREIGN KEY (moderator_id) REFERENCES users (id);

ALTER TABLE posts ADD CONSTRAINT POSTS_USER_ID_FK FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tag2post ADD CONSTRAINT TAG2POST_TAG_ID_FK FOREIGN KEY (tag_id) REFERENCES tags (id);

ALTER TABLE tag2post ADD CONSTRAINT TAG2POST_POST_ID_FK FOREIGN KEY (post_id) REFERENCES posts (id);